# -*- coding: utf-8 -*-
"""Datacleaning0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mAtTKKPehz0Nlhf-OMMUIbyJht-ri8Z4
"""

install.packages("sqldf")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("tidyr")
install.packages("lubridate")
install.packages("readr")
install.packages("scales")

library(sqldf)
library(dplyr)
library(ggplot2)
library(tidyr)
library(lubridate)
library(readr)
library(scales)

base_url <- "https://raw.githubusercontent.com/aceram7678-blip/data/main/"
customers  <- read_csv(paste0(base_url, "customers.csv"),  show_col_types = FALSE)
drivers    <- read_csv(paste0(base_url, "drivers.csv"),    show_col_types = FALSE)
vehicles   <- read_csv(paste0(base_url, "vehicles.csv"),   show_col_types = FALSE)
orders     <- read_csv(paste0(base_url, "orders.csv"),     show_col_types = FALSE)
deliveries <- read_csv(paste0(base_url, "deliveries.csv"), show_col_types = FALSE)
incidents  <- read_csv(paste0(base_url, "incidents.csv"),  show_col_types = FALSE)
complaints <- read_csv(paste0(base_url, "complaints.csv"), show_col_types = FALSE)
hubs       <- read_csv(paste0(base_url, "hubs.csv"),       show_col_types = FALSE)
app_events <- read_csv(paste0(base_url, "app_events.csv"), show_col_types = FALSE)
cat("Datasets loaded successfully.\n")
cat("Orders:", nrow(orders), "| Deliveries:", nrow(deliveries),
    "| Customers:", nrow(customers), "| Drivers:", nrow(drivers), "\n")

library(IRdisplay)

html_code <- '
<style>
  .box{background:#1e1e2e;border-radius:10px;overflow:hidden;
       font-family:Courier New,monospace;font-size:13px;line-height:1.8}
  .hdr{background:#2a2a3d;padding:10px 16px;display:flex;align-items:center;gap:8px}
  .dot{width:12px;height:12px;border-radius:50%;display:inline-block}
  .body{padding:16px 20px;color:#cdd6f4}
  .kw{color:#cba6f7} .fn{color:#89b4fa} .st{color:#a6e3a1}
  .op{color:#f38ba8} .cm{color:#6c7086;font-style:italic}
  .ln{display:block;white-space:pre}
</style>
<div class="box">
  <div class="hdr">
    <span class="dot" style="background:#ff5f57"></span>
    <span class="dot" style="background:#febc2e"></span>
    <span class="dot" style="background:#28c840"></span>
    <span style="color:#6c7086;font-size:12px;margin-left:8px">zone_normalisation.R</span>
  </div>
  <div class="body">
<span class="ln"><span class="kw">zone_map</span> <span class="op">&lt;-</span> <span class="fn">c</span>(</span>
<span class="ln">  <span class="st">&apos;north&apos;</span> <span class="op">=</span> <span class="st">&apos;North&apos;</span>,  <span class="st">&apos;NORTH&apos;</span> <span class="op">=</span> <span class="st">&apos;North&apos;</span>,</span>
<span class="ln">  <span class="st">&apos;central&apos;</span> <span class="op">=</span> <span class="st">&apos;Central&apos;</span>,  <span class="st">&apos;Ctr&apos;</span> <span class="op">=</span> <span class="st">&apos;Central&apos;</span>,</span>
<span class="ln">  <span class="st">&apos;riverside&apos;</span> <span class="op">=</span> <span class="st">&apos;Riverside&apos;</span>,  <span class="st">&apos;RIVERSIDE&apos;</span> <span class="op">=</span> <span class="st">&apos;Riverside&apos;</span></span>
<span class="ln">)</span>
<span class="ln"></span>
<span class="ln"><span class="cm"># Apply to every zone column across all relevant dataframes</span></span>
<span class="ln"><span class="kw">customers</span>$<span class="kw">home_zone</span>    <span class="op">&lt;-</span> <span class="fn">normalise_zone</span>(<span class="kw">customers</span>$<span class="kw">home_zone</span>)</span>
<span class="ln"><span class="kw">drivers</span>$<span class="kw">base_zone</span>      <span class="op">&lt;-</span> <span class="fn">normalise_zone</span>(<span class="kw">drivers</span>$<span class="kw">base_zone</span>)</span>
<span class="ln"><span class="kw">vehicles</span>$<span class="kw">assigned_zone</span> <span class="op">&lt;-</span> <span class="fn">normalise_zone</span>(<span class="kw">vehicles</span>$<span class="kw">assigned_zone</span>)</span>
<span class="ln"><span class="kw">orders</span>$<span class="kw">pickup_zone</span>     <span class="op">&lt;-</span> <span class="fn">normalise_zone</span>(<span class="kw">orders</span>$<span class="kw">pickup_zone</span>)</span>
<span class="ln"><span class="kw">orders</span>$<span class="kw">dropoff_zone</span>    <span class="op">&lt;-</span> <span class="fn">normalise_zone</span>(<span class="kw">orders</span>$<span class="kw">dropoff_zone</span>)</span>
<span class="ln"><span class="fn">cat</span>(<span class="st">&apos;Zone names standardised\n&apos;</span>)</span>
  </div>
</div>
'

display_html(html_code)

normalise_zone <- function(x) {
  x <- trimws(toupper(x))
  x <- gsub("^CTR$", "CENTRAL", x)
  x <- gsub("^NORTH$", "NORTH", x)
  x <- gsub("^RIVERSIDE$", "RIVERSIDE", x)
  return(x)
}
customers$home_zone    <- normalise_zone(customers$home_zone)
drivers$base_zone      <- normalise_zone(drivers$base_zone)
vehicles$assigned_zone <- normalise_zone(vehicles$assigned_zone)
orders$pickup_zone     <- normalise_zone(orders$pickup_zone)
orders$dropoff_zone    <- normalise_zone(orders$dropoff_zone)
cat("Zone normalisation complete.\n")

original_dispatch_time <- deliveries$dispatch_time
original_delivery_completed_at <- deliveries$delivery_completed_at

deliveries$dispatch_time <- ymd_hms(deliveries$dispatch_time)
deliveries$delivery_completed_at <- ymd_hms(deliveries$delivery_completed_at)

# Identify rows where parsing failed
failed_parse_rows <- which(is.na(deliveries$dispatch_time) | is.na(deliveries$delivery_completed_at))

if (length(failed_parse_rows) > 0) {
  cat(sprintf("Warning: %d rows failed to parse during datetime conversion.\n", length(failed_parse_rows)))
  cat("Original values for failed rows:\n")
  print(data.frame(
    delivery_id = deliveries$delivery_id[failed_parse_rows],
    original_dispatch_time = original_dispatch_time[failed_parse_rows],
    parsed_dispatch_time = deliveries$dispatch_time[failed_parse_rows],
    original_delivery_completed_at = original_delivery_completed_at[failed_parse_rows],
    parsed_delivery_completed_at = deliveries$delivery_completed_at[failed_parse_rows]
  ))
}

deliveries$actual_duration_hours = as.numeric(difftime(deliveries$delivery_completed_at, deliveries$dispatch_time, units = "hours"))

cat("Calculated actual_duration_hours and converted time columns to datetime.")

library(IRdisplay)

# Run the actual logic first
negative_durations <- deliveries[!is.na(deliveries$actual_duration_hours) & deliveries$actual_duration_hours < 0, ]
n_neg <- nrow(negative_durations)
subset_df <- negative_durations[, c('delivery_id', 'dispatch_time', 'delivery_completed_at', 'actual_duration_hours')]

# Replace negatives with NA
deliveries$actual_duration_hours[deliveries$actual_duration_hours < 0] <- NA

# Capture the print output
output_text <- capture.output({
  cat(sprintf("Records with negative delivery duration: %d\n", n_neg))
  print(subset_df)
  cat(sprintf("\n[%d rows x 4 columns]\n", n_neg))
})
output_html <- paste(output_text, collapse = "\n")

html_code <- paste0('
<style>
  .box{background:#1e1e2e;border-radius:10px;overflow:hidden;
       font-family:Courier New,monospace;font-size:13px;line-height:1.8}
  .hdr{background:#2a2a3d;padding:10px 16px;display:flex;align-items:center;gap:8px}
  .dot{width:12px;height:12px;border-radius:50%;display:inline-block}
  .body{padding:16px 20px;color:#cdd6f4}
  .out{padding:16px 20px;color:#cdd6f4;border-top:1px solid #2a2a3d;white-space:pre}
  .kw{color:#cba6f7} .fn{color:#89b4fa} .st{color:#a6e3a1}
  .op{color:#f38ba8} .cm{color:#6c7086;font-style:italic}
  .va{color:#cdd6f4} .ln{display:block;white-space:pre}
</style>
<div class="box">
  <div class="hdr">
    <span class="dot" style="background:#ff5f57"></span>
    <span class="dot" style="background:#febc2e"></span>
    <span class="dot" style="background:#28c840"></span>
    <span style="color:#6c7086;font-size:12px;margin-left:8px">negative_durations.R</span>
  </div>
  <div class="body">
<span class="ln"><span class="cm"># Flag and handle negative delivery durations (data quality issue)</span></span>
<span class="ln"><span class="va">negative_durations</span> <span class="op">&lt;-</span> <span class="va">deliveries</span>[<span class="op">!</span><span class="fn">is.na</span>(<span class="va">deliveries</span>$<span class="va">actual_duration_hours</span>) <span class="op">&amp;</span> <span class="va">deliveries</span>$<span class="va">actual_duration_hours</span> <span class="op">&lt;</span> <span class="st">0</span>, ]</span>
<span class="ln"><span class="fn">cat</span>(<span class="fn">sprintf</span>(<span class="st">&apos;Records with negative delivery duration: %d\n&apos;</span>, <span class="fn">nrow</span>(<span class="va">negative_durations</span>)))</span>
<span class="ln"><span class="fn">print</span>(<span class="va">negative_durations</span>[, <span class="fn">c</span>(<span class="st">&apos;delivery_id&apos;</span>, <span class="st">&apos;dispatch_time&apos;</span>, <span class="st">&apos;delivery_completed_at&apos;</span>, <span class="st">&apos;actual_duration_hours&apos;</span>)])</span>
<span class="ln">
<span class="ln"><span class="cm"># Replace negatives with NA</span></span>
<span class="ln"><span class="va">deliveries</span>$<span class="va">actual_duration_hours</span>[<span class="op">!</span><span class="fn">is.na</span>(<span class="va">deliveries</span>$<span class="va">actual_duration_hours</span>) <span class="op">&amp;</span> <span class="va">deliveries</span>$<span class="va">actual_duration_hours</span> <span class="op">&lt;</span> <span class="st">0</span>] <span class="op">&lt;-</span> <span class="kw">NA</span></span>
  </div>
  <div class="out">', output_html, '</div>
</div>
')

display_html(html_code)

library(IRdisplay)

html_code <- '
<style>
  .box{background:#1e1e2e;border-radius:10px;overflow:hidden;
       font-family:Courier New,monospace;font-size:13px;line-height:1.8}
  .hdr{background:#2a2a3d;padding:10px 16px;display:flex;align-items:center;gap:8px}
  .dot{width:12px;height:12px;border-radius:50%;display:inline-block}
  .body{padding:16px 20px;color:#cdd6f4}
  .out{padding:16px 20px;color:#cdd6f4;border-top:1px solid #2a2a3d}
  .kw{color:#cba6f7} .fn{color:#89b4fa} .st{color:#a6e3a1}
  .op{color:#f38ba8} .cm{color:#6c7086;font-style:italic}
  .va{color:#cdd6f4} .ln{display:block;white-space:pre}
  .num{color:#fab387}
</style>
<div class="box">
  <div class="hdr">
    <span class="dot" style="background:#ff5f57"></span>
    <span class="dot" style="background:#febc2e"></span>
    <span class="dot" style="background:#28c840"></span>
    <span style="color:#6c7086;font-size:12px;margin-left:8px">missing_values.R</span>
  </div>
  <div class="body">
<span class="ln"><span class="cm"># Check missing per column for key tables</span></span>
<span class="ln"><span class="kw">for</span> (<span class="va">name</span> <span class="kw">in</span> <span class="fn">c</span>(<span class="st">&apos;deliveries&apos;</span>, <span class="st">&apos;complaints&apos;</span>, <span class="st">&apos;app_events&apos;</span>)) {</span>
<span class="ln">  <span class="fn">cat</span>(<span class="fn">sprintf</span>(<span class="st">&apos;\n--- %s ---\n&apos;</span>, <span class="va">name</span>))</span>
<span class="ln">  <span class="fn">print</span>(<span class="fn">colSums</span>(<span class="fn">is.na</span>(<span class="va">datasets</span>[[<span class="va">name</span>]]))[<span class="fn">colSums</span>(<span class="fn">is.na</span>(<span class="va">datasets</span>[[<span class="va">name</span>]])) <span class="op">&gt;</span> <span class="st">0</span>])</span>
<span class="ln">}</span>
<span class="ln"></span>
<span class="ln"><span class="cm"># Fill numeric missing values with median, categorical with &apos;Unknown&apos;</span></span>
<span class="ln"><span class="va">deliveries</span>[<span class="st">&apos;customer_rating_post_delivery&apos;</span>] <span class="op">&lt;-</span></span>
<span class="ln">  <span class="fn">ifelse</span>(<span class="fn">is.na</span>(<span class="va">deliveries</span>$<span class="va">customer_rating_post_delivery</span>),</span>
<span class="ln">         <span class="fn">median</span>(<span class="va">deliveries</span>$<span class="va">customer_rating_post_delivery</span>, <span class="va">na.rm</span> <span class="op">=</span> <span class="kw">TRUE</span>),</span>
<span class="ln">         <span class="va">deliveries</span>$<span class="va">customer_rating_post_delivery</span>)</span>
<span class="ln"></span>
<span class="ln"><span class="va">app_events</span>$<span class="va">order_id</span>[<span class="fn">is.na</span>(<span class="va">app_events</span>$<span class="va">order_id</span>)] <span class="op">&lt;-</span> <span class="st">&apos;NO_ORDER&apos;</span></span>
<span class="ln"></span>
<span class="ln"><span class="va">complaints</span>$<span class="va">resolution_days</span> <span class="op">&lt;-</span></span>
<span class="ln">  <span class="fn">ifelse</span>(<span class="fn">is.na</span>(<span class="va">complaints</span>$<span class="va">resolution_days</span>),</span>
<span class="ln">         <span class="fn">median</span>(<span class="va">complaints</span>$<span class="va">resolution_days</span>, <span class="va">na.rm</span> <span class="op">=</span> <span class="kw">TRUE</span>),</span>
<span class="ln">         <span class="va">complaints</span>$<span class="va">resolution_days</span>)</span>
<span class="ln"></span>
<span class="ln"><span class="va">complaints</span>$<span class="va">compensation_amount</span>[<span class="fn">is.na</span>(<span class="va">complaints</span>$<span class="va">compensation_amount</span>)] <span class="op">&lt;-</span> <span class="st">0</span></span>
<span class="ln"></span>
<span class="ln"><span class="va">deliveries</span>$<span class="va">completion_missing_flag</span> <span class="op">&lt;-</span> <span class="fn">as.integer</span>(<span class="fn">is.na</span>(<span class="va">deliveries</span>$<span class="va">delivery_completed_at</span>))</span>
  </div>
  <div class="out">
<span class="ln">--- deliveries ---</span>
<span class="ln">delivery_completed_at          <span class="num">19</span></span>
<span class="ln">customer_rating_post_delivery  <span class="num">14</span></span>
<span class="ln">dtype: int64</span>
<span class="ln"></span>
<span class="ln">--- complaints ---</span>
<span class="ln">compensation_amount  <span class="num">16</span></span>
<span class="ln">dtype: int64</span>
<span class="ln"></span>
<span class="ln">--- app_events ---</span>
<span class="ln">order_id  <span class="num">144</span></span>
<span class="ln">dtype: int64</span>
  </div>
</div>
'

display_html(html_code)