# -*- coding: utf-8 -*-
"""SQLINR0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TEpuxQL5VEATtbjyXIIlmVrhcljeIPUa
"""

system('git clone https://github.com/aceram7678-blip/data.git')

# Install and load sqldf package in R
if (!require("sqldf")) install.packages("sqldf", repos="http://cran.us.r-project.org")
library(sqldf)

if (!require("ggplot2")) install.packages("ggplot2", repos="http://cran.us.r-project.org")
library(ggplot2)
if (!require("scales")) install.packages("scales", repos="http://cran.us.r-project.org")
library(scales)

# Load data from the cloned repository
deliveries <- read.csv("data/deliveries.csv")
orders <- read.csv("data/orders.csv")

# Display the first few rows to verify
print(head(deliveries))
print(head(orders))

drivers <- read.csv("data/drivers.csv")
print(head(drivers))

vehicles <- read.csv("data/vehicles.csv")
print(head(vehicles))

complaints <- read.csv("data/complaints.csv")
print(head(complaints))

hubs <- read.csv('data/hubs.csv')
print(head(hubs))

# Join deliveries → orders to get zone context, then count delivery statuses
q1 <- sqldf("
  SELECT
    o.pickup_zone                          AS zone,
    d.delivery_status,
    COUNT(*)                               AS total,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY o.pickup_zone), 1) AS pct
  FROM deliveries d
  JOIN orders o ON d.order_id = o.order_id
  GROUP BY o.pickup_zone, d.delivery_status
  ORDER BY zone, total DESC
")
print(q1)

# Join deliveries → orders to get zone context, then count delivery statuses
q1 <- sqldf("
  SELECT
    o.pickup_zone                          AS zone,
    d.delivery_status,
    COUNT(*)                               AS total,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY o.pickup_zone), 1) AS pct
  FROM deliveries d
  JOIN orders o ON d.order_id = o.order_id
  GROUP BY o.pickup_zone, d.delivery_status
  ORDER BY zone, total DESC
")
print(q1)

library(ggplot2)
library(scales)
ggplot(q1, aes(x = zone, y = total, fill = delivery_status)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_y_continuous(labels = percent_format()) +
  scale_fill_manual(values = c("OnTime"  = "#2ecc71",
                                "Delayed" = "#f39c12",
                                "Failed"  = "#e74c3c")) +
  labs(title    = "Delivery Status Distribution by Pickup Zone",
       subtitle = "NorthStar Urban Mobility – Operational Performance",
       x = "Pickup Zone", y = "Proportion", fill = "Status") +
  theme_minimal(base_size = 13) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

q2 <- sqldf("
  SELECT
    base_zone                              AS zone,
    employment_type,
    COUNT(*)                               AS driver_count,
    ROUND(AVG(driver_rating), 2)           AS avg_rating,
    ROUND(AVG(training_score), 2)          AS avg_training_score,
    SUM(CASE WHEN active_flag = 1 THEN 1 ELSE 0 END) AS active_drivers
  FROM drivers
  GROUP BY base_zone, employment_type
  ORDER BY avg_rating DESC
")
print(q2)

# Aggregate to zone level for chart clarity
driver_zone_summary <- sqldf("
  SELECT base_zone AS zone,
         ROUND(AVG(driver_rating), 2)     AS avg_rating,
         ROUND(AVG(training_score), 2)    AS avg_training,
         COUNT(*)                         AS total_drivers
  FROM drivers
  GROUP BY base_zone
  ORDER BY avg_rating DESC
")
ggplot(driver_zone_summary, aes(x = reorder(zone, -avg_rating), y = avg_rating, fill = avg_training)) +
  geom_bar(stat = "identity") +
  scale_fill_gradient(low = "#f8d7da", high = "#0d6efd") +
  labs(title  = "Average Driver Rating by Zone (colour = Training Score)",
       x = "Zone", y = "Average Rating", fill = "Avg Training\nScore") +
  theme_minimal(base_size = 13) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

q3 <- sqldf("
  SELECT
    vehicle_type,
    maintenance_status,
    COUNT(*)                               AS count,
    ROUND(AVG(battery_health_pct), 1)      AS avg_battery,
    ROUND(AVG(odometer_km), 0)             AS avg_odometer
  FROM vehicles
  WHERE battery_health_pct IS NOT NULL
  GROUP BY vehicle_type, maintenance_status
  ORDER BY vehicle_type, count DESC
")
print(q3)

fleet_status <- sqldf("
  SELECT vehicle_type,
         maintenance_status,
         COUNT(*) AS n
  FROM vehicles
  GROUP BY vehicle_type, maintenance_status
")
ggplot(fleet_status, aes(x = vehicle_type, y = n, fill = maintenance_status)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(values = c("Active"    = "#2ecc71",
                                "Scheduled" = "#3498db",
                                "InRepair"  = "#e74c3c")) +
  labs(title = "Fleet Maintenance Status by Vehicle Type",
       x = "Vehicle Type", y = "Count", fill = "Status") +
  theme_minimal(base_size = 13)

q4 <- sqldf("
  SELECT
    complaint_type,
    severity,
    COUNT(*)                               AS total_complaints,
    ROUND(AVG(resolution_days), 1)         AS avg_resolution_days,
    ROUND(AVG(compensation_amount), 2)     AS avg_compensation,
    SUM(compensation_amount)               AS total_compensation
  FROM complaints
  GROUP BY complaint_type, severity
  ORDER BY total_complaints DESC
")
print(q4)

complaint_summary <- sqldf("
  SELECT complaint_type,
         COUNT(*) AS n,
         ROUND(AVG(resolution_days), 1) AS avg_days
  FROM complaints
  GROUP BY complaint_type
  ORDER BY n DESC
")
ggplot(complaint_summary, aes(x = reorder(complaint_type, -n), y = n, fill = avg_days)) +
  geom_bar(stat = "identity") +
  scale_fill_gradient(low = "#d4edda", high = "#721c24") +
  labs(title  = "Complaint Volume by Type (colour = Avg Resolution Days)",
       x = "Complaint Type", y = "Total Complaints", fill = "Avg Days\nto Resolve") +
  theme_minimal(base_size = 13) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

q5 <- sqldf("
  SELECT
    h.hub_id,
    h.hub_name,
    h.zone,
    h.hub_type,
    h.capacity_score,
    COUNT(d.delivery_id)                   AS total_dispatches,
    ROUND(AVG(d.route_distance_km), 2)     AS avg_route_km,
    SUM(d.manual_route_override_count)     AS total_overrides,
    ROUND(AVG(d.customer_rating_post_delivery), 2) AS avg_customer_rating
  FROM hubs h
  LEFT JOIN deliveries d ON h.hub_id = d.hub_id
  GROUP BY h.hub_id, h.hub_name, h.zone, h.hub_type, h.capacity_score
  ORDER BY total_dispatches DESC
")
print(q5)

q6 <- sqldf("
  SELECT
    d.delivery_status,
    COUNT(d.delivery_id)                   AS deliveries,
    COUNT(i.incident_id)                   AS incidents_linked,
    ROUND(COUNT(i.incident_id) * 100.0 / COUNT(d.delivery_id), 1) AS incident_pct,
    ROUND(AVG(d.manual_route_override_count), 2) AS avg_overrides,
    SUM(d.proof_of_completion_missing)     AS missing_proof_count
  FROM deliveries d
  LEFT JOIN incidents i ON d.delivery_id = i.delivery_id
  GROUP BY d.delivery_status
  ORDER BY deliveries DESC
")
print(q6)

incidents <- read.csv('data/incidents.csv')
print(head(incidents))

customers <- read.csv('data/customers.csv')
print(head(customers))

q7 <- sqldf("
  SELECT
    c.customer_id,
    c.home_zone,
    c.customer_type,
    c.loyalty_score,
    COUNT(o.order_id)              AS total_orders,
    ROUND(SUM(o.order_value), 2)   AS total_spend,
    COUNT(cp.complaint_id)         AS total_complaints,
    ROUND(AVG(cp.compensation_amount), 2) AS avg_compensation
  FROM customers c
  LEFT JOIN orders o  ON c.customer_id = o.customer_id
  LEFT JOIN complaints cp ON c.customer_id = cp.customer_id
  GROUP BY c.customer_id, c.home_zone, c.customer_type, c.loyalty_score
  ORDER BY total_spend DESC
  LIMIT 10
")
print(q7)

# This query uses filtering early to reduce rows before aggregation (optimisation)
q8 <- sqldf("
  SELECT
    o.service_type,
    o.priority_level,
    COUNT(d.delivery_id)                     AS total_deliveries,
    ROUND(AVG(d.fuel_or_charge_cost), 2)     AS avg_fuel_cost,
    ROUND(AVG(d.route_distance_km), 2)       AS avg_distance_km,
    ROUND(AVG(d.fuel_or_charge_cost) /
          NULLIF(AVG(d.route_distance_km),0), 4) AS cost_per_km,
    ROUND(AVG(o.order_value), 2)             AS avg_order_value,
    ROUND(AVG(o.order_value) - AVG(d.fuel_or_charge_cost), 2) AS avg_gross_margin
  FROM orders o
  JOIN deliveries d ON o.order_id = d.order_id
  WHERE d.delivery_status IN ('OnTime', 'Delayed', 'Failed')
  GROUP BY o.service_type, o.priority_level
  ORDER BY avg_gross_margin DESC
")
print(q8)

cat("=== NorthStar SQL in R Summary ===\n\n")
cat("Total Orders:", nrow(orders), "\n")
cat("Total Deliveries:", nrow(deliveries), "\n")
cat("Failed Deliveries:", nrow(deliveries[deliveries$delivery_status == "Failed",]), "\n")
cat("Delayed Deliveries:", nrow(deliveries[deliveries$delivery_status == "Delayed",]), "\n")
cat("Total Complaints:", nrow(complaints), "\n")
cat("Total Incidents:", nrow(incidents), "\n")
cat("Active Vehicles:", nrow(vehicles[vehicles$maintenance_status == "Active",]), "\n")
cat("Vehicles InRepair:", nrow(vehicles[vehicles$maintenance_status == "InRepair",]), "\n")